# Generated by Django 2.2 on 2022-01-07 04:27

from django.db import migrations, models
import instagramapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0005_auto_20220106_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.FileField(upload_to=instagramapp.models.user_directory_path),
        ),
    ]
