# Generated by Django 2.2 on 2022-01-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0007_auto_20220107_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_user', models.ManyToManyField(related_name='other_user', to='instagramapp.Users')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.Users')),
            ],
        ),
    ]
