# Generated by Django 2.2 on 2022-01-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0008_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='other_user',
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', to='instagramapp.Users'),
        ),
    ]
