# Generated by Django 2.2 on 2022-01-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0009_auto_20220108_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='instagramapp.Users'),
        ),
    ]
