# Generated by Django 2.2 on 2022-01-12 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0011_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.Users')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
