# Generated by Django 2.2 on 2022-01-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0014_users_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
