# Generated by Django 2.2 on 2022-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0015_auto_20220113_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.FileField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
