# Generated by Django 2.2 on 2022-01-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0016_auto_20220113_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.Comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.Users')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
