# Generated by Django 2.2 on 2022-01-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0017_subcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomments',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cid', to='instagramapp.Comments'),
        ),
    ]
